# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'loyaltyapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  # Pods for loyaltyapp

  # target 'loyaltyapp-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'loyaltyappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'loyaltyapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for loyaltyapp-tvOS

  target 'loyaltyapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
